app/urls.py
from django.urls import path
from . import views

RenderAppFood = views.RenderAppView()

app_name = 'app'
urlpatterns = [
    path('', RenderAppFood.test, name='principal'),
    path('<slug:foods>/<int:id>/', RenderAppFood.filter_, name='preview'),
    path('category/<str:cat>/', RenderAppFood.filter_category, name='category-food')
]

landing/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.RenderLandingView.test)
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')), # Landing Page
    path('app/', include('app.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

app/models.py
from django.db import models

# Create your models here.


class Job(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField(max_length=50)
    job = models.ForeignKey(to=Job, on_delete=models.SET_NULL, null=True, default=None, blank=True)
    
    def __str__(self):
        return f'{self.name} - {self.job}'

class SubCategory(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Category(models.Model):
    category = models.CharField(max_length=50)
    subcat = models.ManyToManyField(SubCategory)


    def __str__(self):
        return f'{self.category} - {[str(i) for i in self.subcat.all()]}'

class ModelFood(models.Model):
    name = models.CharField(max_length=50)
    author = models.ForeignKey(Author, on_delete=models.SET_DEFAULT, null=True, default='Anônimo', blank=True )
    slug = models.SlugField()
    subtitle = models.TextField(max_length=100)
    category_food = models.ForeignKey(Category, on_delete= models.SET_NULL, null=True, blank=True, default=None)
    
    price = models.DecimalField(decimal_places=2, max_digits=5)
    
    image = models.ImageField(upload_to='user/')
    description = models.TextField(max_length=150)
    
    date_create = models.DateTimeField(auto_now_add=True)
    data_atualization = models.DateTimeField(auto_now=True)

  
    def __str__(self):
        return f'{self.category_food}'
        

landing/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render, get_list_or_404


from . import models

class RenderAppView:
    
    context = {
        'app_food': models.ModelFood.objects.all(),
        'app_user': models.Author.objects.all(),
        'app_test': 'Pedro'
    }
    
    
    def test(self, request):
        return render(
            request, 
            'pages/index.html',
            context= {'context_app_food': self.context}
        )
        
    @staticmethod
    def filter_(request, foods, id):
        
        food = get_list_or_404(models.ModelFood, slug = foods, pk = id)
        
        return render(
            request,
            'pages/list_filter.html',
            context= {'context_app_food': food}
        )
        
    @staticmethod
    def filter_category(request, cat):
        
        food_filter = get_list_or_404(
            models.ModelFood.objects.filter(
            category_food__category = cat, 
        ).order_by('-id')
        
        )
        
        
        return render(
            request, 
            'pages/filter_category.html',
            context= {
                'context_app_food': food_filter            
            }           
        )

landing/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.

class RenderLandingView:
    
    def test(request):
        return HttpResponse('Página landing Page')

app/templates/pages/filter_category.html
<!DOCTYPE html>
<html lang="en">
    {% include "partials/head.html" %}
  <body>
    <div class="container">
      <div class="ctrl-container container-list-filter">
        {% for foods in context_app_food%}
          {% include "partials/block_items.html" %}
        {% endfor %}
      </div>
    </div>
  </body>
</html>

app/templates/pages/index.html
<!DOCTYPE html>
<html lang="en">
    {% include "partials/head.html" %}
  <body>
    <div class="container">
      <div class="ctrl-container">
        {% for foods in context_app_food.app_food %}
          {% include "partials/block_items.html" %}
        {% endfor %}
      </div>
    </div>
  </body>
</html>

app/templates/pages/list_filter.html
<!DOCTYPE html>
<html lang="en">
    {% include "partials/head.html" %}
  <body>
    <div class="container">
      <div class="ctrl-container container-list-filter">
        {% for foods in context_app_food%}
          {% include "partials/block_items.html" %}
        {% endfor %}
      </div>
    </div>
  </body>
</html>

app/templates/partials/block_items.html
<div class="box">
  <div class="image">
    <img class="img" src="{{foods.image.url}}" alt="" />
  </div>
  <div class="content-box">
    <div class="content-title">
      <h1 class="title">{{foods.name}}</h1>
    </div>

    <div class="content-utils">
      <p>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta
        minus, at repellat fugiat sunt porro ipsa numquam consectetur
        soluta quia, reiciendis nisi ullam impedit! Architecto.
      </p>
    </div>
    <div class="author">
      <a href="/">{{foods.author.name}}</a>
    </div>
    <div class="tags">
      <sub>Lorem ipsum dolor sit amet consectetur.</sub>
    </div>
    <div class="content-final">
      <div class="datetime">{{foods.date_create|date:"d/m/Y"}}</div>

      <div class="box-content-links">
        <a href="{% url 'app:category-food' foods.category_food.category %}">{{foods.category_food.category}}</a>
        <a href="/">{{foods.category_food.subcat}}</a>
        <a href="{% url 'app:preview' foods.slug foods.id %}">Saiba Mais</a>
      </div>
    </div>
  </div>
</div>

app/templates/partials/head.html
{% load static %}
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>